apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: expense
  labels:
    app: debug
    env: prod
spec:
  containers:
    - name: debug
      image: cekharch/debug:v1
      command: ["sleep", "10000"]