apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      env: prod
  template:
    metadata:
      labels:
        app: frontend
        env: prod
    spec:
      containers:
        - name: frontend
          image: cekharch/frontend:v11
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: frontend
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: frontend-svc-port