apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
  labels:
    app: backend
    env: prod
data:
  DB_Host: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: prod
  template:
    metadata:
      labels:
        app: backend
        env: prod
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v5
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: prod
spec:
  selector:
    app: backend
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: backend-svc-port