apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
  labels:
    app: backend
    env: prod
data:
  DB_Host: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: prod
  template:
    metadata:
      labels:
        app: backend
        env: prod
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup mysql; do echo waiting for mysql; sleep 2; done"]
          # command: ['sh', '-c', "until nslookup mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done"]

      containers:
        - name: backend
          image: cekharch/backend:v7
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: prod
spec:
  selector:
    app: backend
    env: prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: backend-svc-port